config/routes.rb
Rails.application.routes.draw do
  root 'stores#index'

  resources :articles
  resources :stores

  namespace :services, defaults: { format: :json } do
    resources :stores, only: [:index]
    resources :articles, only: [:index]
    get 'articles/stores/:id', to: 'articles_stores#show', as: 'store_articles'
  end

  get "/400" => "errors#bad_request"
  get "/401" => "errors#not_authorized"
  get "/404" => "errors#not_found"
  get "/500" => "errors#exception"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :store, optional: true

  validates :name, :description, :price, :total_in_shelf, :total_in_vault, :store, presence: true
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :articles

  validates :name, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, unless: -> { request.format.json? }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show; end
  def edit; end

  def new
    @article = Article.new
  end


  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:name, :description, :price, :total_in_shelf, :total_in_vault, :store_id)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def bad_request
    if env["REQUEST_PATH"] =~ /^\/services/
      render json: ErrorsDecorator.new(400).as_json, status: 400
    else
      render text: "400 Not found", status: 400
    end
  end

  def not_authorized
    if env["REQUEST_PATH"] =~ /^\/services/
      render json: ErrorsDecorator.new(401).as_json, status: 401
    else
      render text: "401 Not authorized", status: 401
    end
  end

  def not_found
    if env["REQUEST_PATH"] =~ /^\/services/
      render json: ErrorsDecorator.new(404).as_json, status: 404
    else
      render text: "404 Not found", status: 404
    end
  end

  def exception
    if env["REQUEST_PATH"] =~ /^\/services/
      render json: ErrorsDecorator.new(500).as_json, status: 500
    else
      render text: "500 Internal Server Error", status: 500
    end
  end
end

app/controllers/services/articles_controller.rb
class Services::ArticlesController < Services::BaseController
  def index
    render json: ArticlesDecorator.new(Article.all).as_json, status: 200
  end
end

app/controllers/services/articles_stores_controller.rb
class Services::ArticlesStoresController < Services::BaseController
  before_action :set_store, only: [:show]

  def show
    if @store
      render json: ArticlesDecorator.new(@store.articles).as_json, status: 200
    else
      handle_errors
    end
  end

protected
  def set_store
    @store = Store.where(id: params[:id]).first
  end

  def handle_errors
    Integer(params[:id]) rescue 
      return render json: { "error_msg": "Bad Request","error_code": 400, "success": false }, status: 400


    unless @store
      return render json: {"error_msg": "Record not Found", "error_code": 404, "success": false}, status: 404 
    end
  end
end

app/controllers/services/base_controller.rb
class Services::BaseController < ApplicationController
  # http_basic_authenticate_with name: "my_user", password: "my_password"

  before_action :authenticate

  protected

  def authenticate
    auth || unauth
  end

  def auth
    authenticate_with_http_basic do |username, password|
      username == 'my_user' && password == 'my_password'
    end
  end

  def unauth
    self.headers['WWW-Authenticate'] = 'Basic realm="Clients"'
    respond_to do |format|
      format.json { render json: ErrorsDecorator.new(401).as_json, status: 401 }
    end
  end
end

app/controllers/services/stores_controller.rb
class Services::StoresController < Services::BaseController
  def index
    render json: StoresDecorator.new(Store.all).as_json, status: 200
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  def index
    @stores = Store.all
  end

  def show; end

  def new
    @store = Store.new
  end

  def edit; end

  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div class="row">
      <div class="col s12">
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col s12">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= f.label :total_in_shelf %>
      <%= f.text_field :total_in_shelf %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= f.label :total_in_vault %>
      <%= f.text_field :total_in_vault %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= f.label :store_id %>
      <%= f.select :store_id, options_from_collection_for_select(Store.all, 'id', 'name'),{prompt: "Select an store for this article"}, { class: "browser-default"} %>
    </div>
  </div>

  <div class="row">
    <div class="col s3">
      <%= f.submit class: "white-text waves-effect waves-light blue btn" %>
    </div>
    <div class="col s2 center-align">
      <%= link_to 'Back', articles_path, class: "back_link" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h3>Editing Article</h3>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Articles</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Total in shelf</th>
      <th>Total in vault</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.description %></td>
        <td><%= article.price %></td>
        <td><%= article.total_in_shelf %></td>
        <td><%= article.total_in_vault %></td>
        <td><%= article.store.name %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="row center-align">
  <%= link_to 'New Article', new_article_path, class: "white-text waves-effect waves-light blue btn" %>
</div>

app/views/articles/new.html.erb
<h3>New Article</h3>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @article.price %>
</p>

<p>
  <strong>Total in shelf:</strong>
  <%= @article.total_in_shelf %>
</p>

<p>
  <strong>Total in vault:</strong>
  <%= @article.total_in_vault %>
</p>

<p>
  <strong>Store:</strong>
  <%= @article.store.name %>
</p>


<div class="row">
  <div class="col s2 center-align">
    <%= link_to 'Edit', edit_article_path(@article), class: "white-text waves-effect waves-light blue btn"  %>
  </div>
  <div class="col s2 center-align">
    <%= link_to 'Back', articles_path, class: "back_link"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperShoes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
  </head>
  <body>
    <header>
      <nav class="light-blue lighten-1" role="navigation">
        <div class="nav-wrapper container">
          <div class="brand-logo">
            <%= link_to "Super Shoes", root_path %>
          </div>

          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>

          <ul class="right hide-on-med-and-down">
            <li><%= link_to "Stores", stores_path %></li>
            <li><%= link_to "Articles", articles_path %></li>
          </ul>


          <ul id="nav-mobile" class="side-nav">
            <li><%= link_to "Stores", stores_path %></li>
            <li><%= link_to "Articles", articles_path %></li>
          </ul>

        </div>
      </nav>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer class="blue">
      <div class="footer-copyright">
        <div class="container">
          <p class="white-text">© 2016 Copyright</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/stores/_form.html.erb
<%= form_for(store) do |f| %>
  <% if store.errors.any? %>
    <div class="row">
      <div class="col s12">
        <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

        <ul>
        <% store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col s12">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
  </div>

  <div class="row">
    <div class="col s3">
      <%= f.submit class: "white-text waves-effect waves-light blue btn" %>
    </div>
    <div class="col s2 center-align">
      <%= link_to 'Back', stores_path, class: "back_link"%> <br>
    </div>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h3>Editing Store</h3>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Stores</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Delete', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="row center-align">
  <%= link_to 'New Store', new_store_path, class: "white-text waves-effect waves-light blue btn" %>
</div>

app/views/stores/new.html.erb
<h3>New Store</h3>

<%= render 'form', store: @store %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Articles</strong>
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Total in shelf</th>
      <th>Total in vault</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @store.articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.description %></td>
        <td><%= article.price %></td>
        <td><%= article.total_in_shelf %></td>
        <td><%= article.total_in_vault %></td>
        <td><%= article.store.name %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col s2 center-align">
    <%= link_to 'Edit', edit_store_path(@store), class: "white-text waves-effect waves-light blue btn"  %>
  </div>
  <div class="col s2 center-align">
    <%= link_to 'Back', stores_path, class: "back_link"%> <br>
  </div>
</div>